version: "3.9"

services:
  backend:
    build: ./backend
    container_name: pdf_mas_backend
    volumes:
      - ./backend/uploads:/app/uploads
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: pdf_mas_frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
